### ISSUE TITLE
Uncaught error: np.on is not a function

### ISSUE THREAD

**Issue by nightpool** [anicolao/npa#13]
Downloaded the game today, saw this in the console:

<img width="425" alt="image" src="https://github.com/user-attachments/assets/18b2ede4-9af7-459a-aa34-2ba8156bd244">

**Comment by nightpool** [comment]
Also seems like it's not binding the `this` of the server response properly:
<img width="556" alt="image" src="https://github.com/user-attachments/assets/5edc06ca-d9c3-49d3-a6a1-c067719cc800">

**Comment by anicolao** [comment]
So excited to see someone engaging on github!

I am thinking that you must be on the wrong version. You need "Neptune's Pride Agent αλφα Edition" for NP4. Stable only works against triton, and triton is being taken down and support for it being removed by the game developer and therefore also by the extension eventually. What platform are you on, and what version do you have?

**Comment by nightpool** [comment]
@anicolao Thanks, that wasn't clear from the Chrome Store listing—I read some reviews about it not being updated, but then I saw the Github was active. When I loaded the unpacked version from `main`, this is the error I got:

```
Uncaught (in promise) ReferenceError: Cannot access 'colorMap' before initialization
    at rebuildColorMap (intel.ts:1396:50)
    at recordTrueTick (intel.ts:1453:5)
    at onTrigger (intel.ts:192:9)
    at NeptunesPrideAgent (intel.ts:1456:3)
```

<img width="292" alt="image" src="https://github.com/user-attachments/assets/68993685-18b0-4759-b857-11e45825d4d5">

**Comment by anicolao** [comment]
You've followed the directions in DEVELOPMENT.md to build the `dist` directory, and then turned on dev mode and loaded from there?

What operating system + browser?

**Comment by nightpool** [comment]
Correct. Mac + Chrome 130

**Comment by anicolao** [comment]
Hmm. I'm on 
129.0.6668.101 (Official Build) (arm64) 
am I behind?

**Comment by nightpool** [comment]
Ah, actually you're right: I'm on 129 on one laptop and 130 on the other laptop. 129 was where I was having the issues

**Comment by anicolao** [comment]
Meant to be fixed by https://github.com/anicolao/npa/commit/5a62ee456da926a4e58ec9557d1446815c163520

Can you try again and let me know?
